### PR TITLE
Add publish parameter to delete methods.

### PR DESCRIPTION
**Pull request by anothrNick**
& check publish parameter and implicitPublish.

### CODE REVIEW

**Comment by whisk3y** [comment]
+1 looks good

@Marchowes

**Comment by Marchowes** [comment]
You forgot `DSFFailoverChain` Which is not surprising since its easily forgotten :)

Are our customers just looking for this for DSF services? What about Monitors/Notifiers? They probably don't want those, but I figured I'd ask just in case.

**Comment by anothrNick** [comment]
Thanks I'll update `DSFFailoverChain` as well.

The docs for Monitors/Notifiers don't mention support for the publish parameter, so I left those out:
https://help.dyn.com/delete-dsf-monitor-api/
https://help.dyn.com/delete-notifier-api/

**Comment by anothrNick** [comment]
Updated

**Comment by Marchowes** [comment]
if you update the HISTORY.rst file, I'll go ahead and merge this.

**Comment by anothrNick** [comment]
Updated HISTORY.rst @Marchowes

**Pull request merged**
